### ISSUE TITLE
Plugin is not working 

### ISSUE THREAD

**Issue by 9olon19** [NodeBB/nodebb-plugin-customize#1]
Hi,

I installed, activated the plugin and restart nodebb, but can't access the plugin main page when browsing to plugins/customize. no error message, just a spinning wheel.

Nodebb version v1.13.0

Thanks

**Comment by julianlam** [comment]
Please make sure you rebuild NodeBB assets as well

**Comment by 9olon19** [comment]
> Please make sure you rebuild NodeBB assets as well

Rebuild and restart still have the same problem.

**Comment by pitaj** [comment]
Are there any errors in the server log or client-side in the JavaScript console of your browser?

**Comment by amargon** [comment]
Hi! I have the same issue, it happens after every Rebuild&Restart (and there are no errors in the log). A bit later the plugin page opens (still nothing in the log), but the plugin does not compile new assets — and there IS an error in the log finally, because NodeBB crashes:

```
uncaughtException: cb.apply is not a function
TypeError: cb.apply is not a function
    at /opt/nodebb/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:159:5) {"error":{},"stack":"TypeError: cb.apply is not a function\n    at /opt/nodebb/node_modules/graceful-fs/polyfills.js:285:20\n    at FSReqCallback.oncomplete (fs.js:159:5)","exception":true,"date":"Fri Nov 22 2019 20:45:53 GMT+0000 (Coordinated Universal Time)","process":{"pid":6235,"uid":998,"gid":998,"cwd":"/opt/nodebb","execPath":"/usr/bin/node","version":"v12.13.1","argv":["/usr/bin/node","/opt/nodebb/app.js"],"memoryUsage":{"rss":150892544,"heapTotal":104361984,"heapUsed":92386496,"external":37746164}},"os":{"loadavg":[0.16015625,0.033203125,0.0107421875],"uptime":566550},"trace":[{"column":20,"file":"/opt/nodebb/node_modules/graceful-fs/polyfills.js","function":null,"line":285,"method":null,"native":false},{"column":5,"file":"fs.js","function":"FSReqCallback.oncomplete","line":159,"method":"oncomplete","native":false}]}
cb.apply is not a function
```

**Comment by pitaj** [comment]
Closing this because I've released a version since.
